name: Validate ROS2 Nodes

on:
  schedule:
    - cron: '0 22 * * *'

  push:
    branches:
      - main

jobs:
  validate_ros2_nodes:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS2 Humble
        run: |
          sudo apt update && sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep
          sudo rosdep init || true
          rosdep update

      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build

      # 各ノードの起動と確認
      - name: Validate Roboware_node
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          nohup ros2 run Robowarepkg Roboware_node > roboware_node.log 2>&1 &
          sleep 5  # ノード起動を待機
          pkill -f "ros2 run Robowarepkg Roboware_node"  # ノードを停止
          if grep -q "ERROR" roboware_node.log; then
            cat roboware_node.log
            exit 1
          fi

      - name: Validate serial_send_node
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          nohup ros2 run Robowarepkg serial_send_node > serial_send_node.log 2>&1 &
          sleep 5
          pkill -f "ros2 run Robowarepkg serial_send_node"
          if grep -q "ERROR" serial_send_node.log; then
            cat serial_send_node.log
            exit 1
          fi

      - name: Validate serial_read_node
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          nohup ros2 run Robowarepkg serial_read_node > serial_read_node.log 2>&1 &
          sleep 5
          pkill -f "ros2 run Robowarepkg serial_read_node"
          if grep -q "ERROR" serial_read_node.log; then
            cat serial_read_node.log
            exit 1
          fi

      - name: Validate web_socket_node
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          nohup ros2 run Robowarepkg web_socket_node > web_socket_node.log 2>&1 &
          sleep 5
          pkill -f "ros2 run Robowarepkg web_socket_node"
          if grep -q "ERROR" web_socket_node.log; then
            cat web_socket_node.log
            exit 1
          fi
